# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  - board: nrfmicro_13
    shield: corne_left
  - board: nrfmicro_13
    shield: corne_right
  - board: nrfmicro_13
    shield: settings_reset    
# 取消注释可以开启nice!nano主控固件默认情况下为关闭模式
#  - board: nice_nano_v2
#    shield: corne_left
#  - board: nice_nano_v2
#  - board: nice_nano_v2
#    shield: corne_right
#  - board: nice_nano_v2
#    shield: settings_reset
