manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: nvhung9
      url-base: https://github.com/nvhung9
    - name: nguyendown
      url-base: https://github.com/nguyendown
    - name: mozixun-me
      url-base: https://github.com/mozixun-me
  projects:
    - name: soflezmk
      remote: mozixun-me
      revision: sofle-bongo-cat
      import: app/west.yml
  self:
    path: config
