manifest:
  remotes:
    - name: mozixun-me
      url-base: https://github.com/mozixun-me
  projects:
    - name: mozixun-me
      remote: zmk-bongo-cat
      revision: main
      import: app/west.yml
  self:
    path: config
